[project]
name = "pyinstaller-cicd"
version = "0.1.0"
description = "Making a package with pyinstaller"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pyinstaller>=6.14.1",
    "pyqt5>=5.15.11",
]
