# .github/workflows/pyinstaller-build.yml

name: Build(Win / Mac-Arm64) with PyInstaller

on:
  push:
    tags:
      - 'v*'  # v1.0.0 などのタグをpushしたときに動く
  workflow_dispatch:  # 手動でワークフローをトリガー可能にする

jobs:
  win_build:
    runs-on: windows-latest  # Windowsビルド
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: List the current directory contents
        run: |
          echo "Current directory contents:"
          Get-ChildItem -Force  # 現在のディレクトリの内容を詳細表示

      - name: List installed packages (debug step)
        run: |
          uv pip list  # インストールされているパッケージを表示

      - name: Build executable
        run: |
          uv run pyinstaller app.py --onefile --distpath dist --name app_win.exe  # pyinstallerでビルド

      - name: List the current directory contents
        run: |
          echo "Current directory contents:"
          Get-ChildItem -Force  # 現在のディレクトリの内容を詳細表示

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-win-exe
          path: dist/app_win.exe

  mac_arm64_build:
    runs-on: macos-15  # Mac_Arm64ビルド
    needs: win_build  # 'win_build' ジョブが成功してから実行
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      
      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: List the current directory contents
        run: |
          echo "Current directory contents:"
          ls -alh  # 現在のディレクトリの内容を詳細表示

      - name: List installed packages (debug step)
        run: |
          uv pip list  # インストールされているパッケージを表示

      - name: Build executable
        run: |
          uv run pyinstaller app.py --onefile --distpath dist --name app_mac_arm64  # Mac_arm64用のビルド

      - name: List the current directory contents
        run: |
          echo "Current directory contents:"
          ls -alh  # 現在のディレクトリの内容を詳細表示

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-mac-arm64
          path: dist/app_mac_arm64

  release:
    runs-on: ubuntu-latest
    needs: mac_arm64_build  # 'mac_arm64_build' ジョブが成功してから実行
    steps:
      - name: List the current directory contents
        run: |
          echo "Current directory contents:"
          ls -alh  # 現在のディレクトリの内容を詳細表示

      - name: Download artifact (Windows)
        uses: actions/download-artifact@v4
        with:
          name: app-win-exe

      - name: Download artifact (Mac)
        uses: actions/download-artifact@v4
        with:
          name: app-mac-arm64

      - name: List the current directory contents
        run: |
          echo "Current directory contents:"
          ls -alh  # 現在のディレクトリの内容を詳細表示

      - name: Create Release and Upload
        uses: softprops/action-gh-release@v2
        with:
          files: |
            app_win.exe
            app_mac_arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}