# .github/workflows/pyinstaller-build.yml

name: Build (Win / Mac-Arm64) with PyInstaller

on:
  push:
    tags:
      - 'v*'  # Runs when a tag like v1.0.0 is pushed
  workflow_dispatch:  # Allows manual triggering of the workflow

permissions:
  contents: write

jobs:
  win_build:
    runs-on: windows-latest  # Windows build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: List the current directory contents
        run: |
          echo "Current directory contents:"
          Get-ChildItem -Force  # Show detailed contents of the current directory

      - name: List installed packages (debug step)
        run: |
          uv pip list  # Show installed packages

      - name: Build executable
        run: |
          uv run pyinstaller app.py --onefile --distpath dist --name app_win.exe  # Build with pyinstaller

      - name: List the current directory contents
        run: |
          echo "Current directory contents:"
          Get-ChildItem -Force  # Show detailed contents of the current directory

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-win-exe
          path: dist/app_win.exe

  mac_arm64_build:
    runs-on: macos-15  # Mac_Arm64 build
    needs: win_build  # Runs after 'win_build' job succeeds
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      
      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: List the current directory contents
        run: |
          echo "Current directory contents:"
          ls -alh  # Show detailed contents of the current directory

      - name: List installed packages (debug step)
        run: |
          uv pip list  # Show installed packages

      - name: Build executable
        run: |
          uv run pyinstaller app.py --onefile --distpath dist --name app_mac_arm64  # Build for Mac_arm64

      - name: List the current directory contents
        run: |
          echo "Current directory contents:"
          ls -alh  # Show detailed contents of the current directory

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-mac-arm64
          path: dist/app_mac_arm64

  release:
    runs-on: ubuntu-latest
    needs: mac_arm64_build  # Runs after 'mac_arm64_build' job succeeds
    steps:
      - name: Download artifact (Windows)
        uses: actions/download-artifact@v4
        with:
          name: app-win-exe

      - name: Download artifact (Mac)
        uses: actions/download-artifact@v4
        with:
          name: app-mac-arm64

      - name: List the current directory contents
        run: |
          echo "Current directory contents:"
          ls -alh  # Show detailed contents of the current directory

      - name: Create Release and Upload
        uses: softprops/action-gh-release@v2
        with:
          files: |
            app_win.exe
            app_mac_arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}