# .github/workflows/pyinstaller-build.yml

name: Build(Win / Max) with PyInstaller

on:
  push:
    tags:
      - 'v*'  # v1.0.0 などのタグをpushしたときに動く
  workflow_dispatch:  # 手動でワークフローをトリガー可能にする

jobs:
  win_build:
    runs-on: windows-latest  # Windowsビルド
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # 仮想環境内に依存関係をインストール

      - name: List the current directory contents
        run: |
          echo "Current directory contents:"
          Get-ChildItem -Force  # 現在のディレクトリの内容を詳細表示

      - name: List installed packages (debug step)
        run: |
          pip list  # インストールされているパッケージを表示

      - name: Build executable
        run: |
          pyinstaller app.py --onefile --distpath dist --name app.exe  # pyinstallerでビルド

      - name: List the current directory contents
        run: |
          echo "Current directory contents:"
          Get-ChildItem -Force  # 現在のディレクトリの内容を詳細表示

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-exe
          path: dist/app.exe

  mac_build:
    runs-on: macos-latest  # Macビルド
    needs: win_build  # 'win_build' ジョブが成功してから実行
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # 仮想環境内に依存関係をインストール

      - name: List the current directory contents
        run: |
          echo "Current directory contents:"
          ls -alh  # 現在のディレクトリの内容を詳細表示

      - name: List installed packages (debug step)
        run: |
          pip list  # インストールされているパッケージを表示

      - name: Build executable
        run: |
          pyinstaller app.py --onefile --distpath dist --name app  # Mac用のビルド

      - name: List the current directory contents
        run: |
          echo "Current directory contents:"
          ls -alh  # 現在のディレクトリの内容を詳細表示

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-mac
          path: dist/app

  release:
    runs-on: ubuntu-latest
    needs: mac_build  # 'mac_build' ジョブが成功してから実行
    steps:
      - name: List the current directory contents
        run: |
          echo "Current directory contents:"
          ls -alh  # 現在のディレクトリの内容を詳細表示

      - name: Download artifact (Windows)
        uses: actions/download-artifact@v4
        with:
          name: app-exe

      - name: Download artifact (Mac)
        uses: actions/download-artifact@v4
        with:
          name: app-mac

      - name: List the current directory contents
        run: |
          echo "Current directory contents:"
          ls -alh  # 現在のディレクトリの内容を詳細表示

      - name: Create Release and Upload
        uses: softprops/action-gh-release@v1
        with:
          files: |
            app.exe
            app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}