# .github/workflows/pyinstaller-build.yml

name: Build with PyInstaller

on:
  push:
    tags:
      - 'v*'  # v1.0.0 などのタグをpushしたときに動く
  workflow_dispatch:  # 手動でワークフローをトリガー可能にする

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Create virtual environment
        run: |
          python -m venv venv  # 仮想環境を作成

      - name: Install dependencies
        run: |
          .\venv\Scripts\activate  # 仮想環境をアクティブにする
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # 仮想環境内に依存関係をインストール

      - name: List the current directory contents
        run: |
          echo "Current directory contents:"
          Get-ChildItem -Force  # 現在のディレクトリの内容を詳細表示

      - name: List installed packages (debug step)
        run: |
          pip list  # インストールされているパッケージを表示

      - name: Build executable
        run: |
          pyinstaller app.py --onefile --distpath dist --name app.exe  # pyinstallerでビルド

      - name: List the current directory contents
        run: |
          echo "Current directory contents:"
          Get-ChildItem -Force  # 現在のディレクトリの内容を詳細表示

      - name: List dist directory contents (debug step)
        run: |
          dir dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-exe
          path: dist/app.exe

  release:
    runs-on: ubuntu-latest
    needs: build  # 'build' ジョブが成功してから実行

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: app-exe

      - name: Create Release and Upload
        uses: softprops/action-gh-release@v1
        with:
          files: dist/app.exe  # リリースにアップロードするファイル
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}